version : '3'
services:
  db:
    build:
      context: ./build/package/docker/MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
      - "3307:3306"
    tty: true
  app:
    build:
      context: ./build/package/docker/Go
    volumes:
      - "./:/go/src/docker-grab"
    container_name: golang_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db